/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Main from "@/Components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Findy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/icon-logo.png" />
      </Head>
      <Main/>
      <div className={styles.container}>
        <h2>Findy ajudando voce a<br/> enccontra algo que ama.</h2>
        <p>“São Longuinho, São Longuinho, se eu achar...”<br/> Vamos lá!</p>
      </div>
    </>
  );
}
